[package]
name = "tectonics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vek = "0.16.1"
minifb = "0.25"
rand = "0.8.5"
noise = "0.8.2"
rand_chacha = "0.3.1"
hashbrown = "0.14.0"
